version: '0.1'

services:
  app:
    build: ./
    command: node index.js
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - /home/boris/web/test/index.js:/usr/src/index.js
      - /home/boris/web/test/package.json:/usr/src/package.json
      - /home/boris/web/test/node_modules:/usr/src/node_modules
    environment:
      MYNAME: BORIS